on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed.

jobs:
  infracost:
    name: Run Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      TF_ROOT: ec2/  # Use TF_ROOT for clarity

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          working-directory: ${{ env.TF_ROOT }}

      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform plan
        run: terraform plan -out=tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform show
        run: | 
           terraform show -json tfplan.binary > /tmp/plan.json
           ls -la && pwd && ls /tmp/
        working-directory: ${{ env.TF_ROOT }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
           api-key: ${{ secrets.INFRACOST_API_KEY }}
           working-directory: ${{ env.TF_ROOT }}
      - name: ls    
        run: |
           ls /tmp/

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'
      - name: ls    
        run: |
           ls /tmp/

      - name: Infracost breakdown
        run: |
           ls -la && pwd && ls /tmp/
           infracost breakdown --path=/tmp/plan.json --format=json --out-file=/tmp/infracost-base.json
        working-directory: ${{ env.TF_ROOT }}
        
      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v4
    
        
      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          ls -la
          infracost diff --path=/tmp/plan.json \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
        working-directory: ${{ env.TF_ROOT }}

      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost-base.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ github.token }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update
