on:
  pull_request:
    branches:
      - main

jobs:
  infracost:
    name: Run Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      TF_ROOT: ec2/

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          working-directory: ${{ env.TF_ROOT }}

      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform plan
        run: terraform plan -out=tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform show
        run: |
          terraform show -json tfplan.binary > plan.json
          ls -la && pwd && ls /tmp/
        working-directory: ${{ env.TF_ROOT }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          working-directory: ${{ env.TF_ROOT }}

      - name: Infracost breakdown
        run: |
          ls -la && pwd && ls /tmp/
          infracost breakdown --path=plan.json --format=json --out-file=/tmp/infracost-base.json
        working-directory: ${{ env.TF_ROOT }}
        
      - name: Generate Infracost diff
        run: |
          ls -la
          infracost diff --path=plan.json \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
        working-directory: ${{ env.TF_ROOT }}

      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost-base.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ github.token }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update
